django/shopping_mall/admins/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('',views.index,name='index'),
]

django/shopping_mall/shopping/urls.py
from django.urls import path
from . import views



urlpatterns=[
    path('',views.homepage,name='homepage'),
    path('login/',views.login,name='login'),
    path('logout/',views.logout,name='logout'),
    path('register/',views.register,name='register'),
    path('user_center_info/',views.user_center_info,name='user_center_info'),
    path('cart/',views.cart,name='cart'),
    path('user_center_order/',views.user_center_order,name='user_center_order'),
    path('detail/<int:a>/',views.detail,name='detail'),
    path('list/<int:a>',views.list,name='list'),
    path('list/<int:a>?<int:b>/',views.list,name='list'),
    path('user_center_site/',views.user_center_site,name='user_center_site'),
    path('place_order/',views.place_order,name='place_order'),
    path('shop/',views.shop,name='shop'),
    path('dell/<int:q>/',views.dell,name='dell'),
    path('add/',views.add,name='add'),
    path('add1/',views.add1,name='add1'),
    path('gai/',views.gai,name='gai'),
    path('goumai/',views.goumai,name='goumai'),
    path('create_index/',views.create_index,name='create_index'),
    path('search/',views.search,name='search'),
    path('qfk/',views.qfk,name='qfk')
]

django/shopping_mall/shopping_mall/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.urls import re_path
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admins/', include('admins.urls')),
    path('',include('shopping.urls'))
]

if settings.DEBUG:
    urlpatterns += [
        re_path(r'^media/(?P<path>.*)$',serve,{
            'document_root':settings.MEDIA_ROOT
        })
    ]

django/shopping_mall/shopping/models.py
from django.db import models
from  django.contrib.auth.models import AbstractUser


#商品分类表
class Goods_type(models.Model):
    class Meta:
        verbose_name = '商品分类'
        verbose_name_plural = verbose_name
    name = models.CharField('名称',max_length=10,null=True)
    img1 = models.ImageField('图片1-图标',upload_to='img/',null=True)
    note = models.CharField ('说明',max_length=255,null=True)
    ctime = models.DateTimeField('创建时间',auto_now_add=True)
    icon = models.CharField('图标',max_length=20,null=True)

    def __str__(self):
        return self.name
#商品表
class Goods(models.Model):
    class Meta:
        verbose_name = '商品'
        verbose_name_plural = verbose_name
    name = models.CharField('名称',max_length=50,null=True)
    img1 = models.ImageField('商品图片1',upload_to='img/',null=True)
    seller = models.IntegerField('卖家编号',default=1)
    goods_info = models.CharField('商品详情',max_length=255,null=True)
    is_buy = models.IntegerField('是否上架',choices=((0,'NO'),(1,'上架')),default=1)
    zyxs = models.IntegerField('主页显示',choices=((0,'NO'),(1,'主页显示')),default=1) #zyxs:主页显示
    tj = models.IntegerField('新品推荐',choices=((0,'NO'),(1,'推荐')),default=0)#tj:推荐
    price = models.FloatField('价格',default=0)
    unit = models.CharField('商品单位',max_length=50,default='500g')
    goods = models.ForeignKey(Goods_type, on_delete=models.CASCADE, verbose_name='商品种类')

    def __str__(self):
        return self.name
# 用户表
class User(AbstractUser):

    class Meta:
        verbose_name = '用户'
        verbose_name_plural = verbose_name

    # name = models.CharField('姓名',max_length=30,null=False)
    nick = models.CharField('昵称',max_length=30,null=True)
    ctime = models.DateTimeField('创建时间',auto_now_add=True,null=True)
    birthday = models.DateTimeField('生日',null=True)
    # email = models.EmailField('邮箱')
    tel = models.CharField('电话',max_length=11,null=False)
    # pwd = models.CharField('密码',max_length=36,null=False)
    age = models.SmallIntegerField('年龄',null=True)
    sex = models.SmallIntegerField('性别',choices=((0,'女'),(1,'男')),default=0)
    home_addr = models.CharField('住址',max_length=255)
    account = models.CharField('账号',max_length=20)
    goods1 = models.ManyToManyField(Goods,through='Shop_cart',through_fields=('user','goods1'),verbose_name='商品')

    # def __str__(self):
    #     return self.username

#收货地址
class Addr(models.Model):

    class Meta:
        verbose_name = '收货地址'
        verbose_name_plural = verbose_name

    name = models.CharField('收件人',max_length=10)
    site = models.CharField('详细地址',max_length=150,null=True)
    Zip_Code = models.IntegerField('邮编',null=True)
    tel = models.CharField('电话',max_length=12)
    user =models.ForeignKey(User,on_delete=models.CASCADE,verbose_name='用户编号')

    def __str__(self):
        return self.name
# 首页轮播图
class Banner(models.Model):
    class Meta:
        verbose_name = '轮播图'
        verbose_name_plural = verbose_name

    name = models.CharField('名字',max_length=50)
    img = models.ImageField('图片',upload_to='img/')
    title = models.IntegerField('标题',choices=((0,'静态图片'),(1,'轮播图')),default=0)
    status = models.IntegerField('是否启用',choices=((0,'不启用'),(1,'启用')),default=1)

    def __str__(self):
        return self.name
#购物车(User和Goods多对多建表)
class Shop_cart(models.Model):  #status: 状态；现状
    class Meta:
        verbose_name = '购物车'
        verbose_name_plural = verbose_name

    count = models.IntegerField('数量',null=True)
    status = models.IntegerField('是否启用',choices=((0,'NO'),(1,'启用')),default=1)
    ljgm = models.IntegerField('立即购买', choices=((0, 'NO'), (1, 'YES')), default=0)
    is_del = models.IntegerField('是否删除',choices=((0,'NO'),(1,'删除')),default=0)
    goods1 = models.ForeignKey(Goods,on_delete=models.CASCADE,verbose_name='商品编号')
    user = models.ForeignKey(User,on_delete=models.CASCADE,verbose_name='用户编号')

#支付平台
class Pay_type(models.Model):
    class Meta:
        verbose_name = '支付平台'
        verbose_name_plural = verbose_name

    name = models.CharField('支付类型名称',max_length=50,null=True)
    status = models.IntegerField('是否启用',choices=((0,'NO'),(1,'启用')),default=1)
    img = models.CharField('支付平台图标',max_length=50)

    def __str__(self):
        return self.name

#订单
class Order(models.Model):
    class Meta:
        verbose_name = '订单'
        verbose_name_plural = verbose_name

    ctime = models.DateTimeField('订单生成时间', auto_now_add=True)
    itmes = models.CharField('订单号',max_length=50,null=True)
    order_status = models.IntegerField('订单状态', choices=((0, '未付款'), (1, '已付款')), default=1)
    status = models.IntegerField('付款/查看', choices=((0, '去付款'), (1, '查看物流')), default=1)
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='用户编号')

    # def __str__(self):
    #     return self.name

#订单详情
class Order_goods(models.Model):
    class Meta:
        verbose_name = '订单详情'
        verbose_name_plural = verbose_name

    total1 = models.FloatField('商品小计',null=True)
    num1 = models.IntegerField('商品数量',null=True)
    goods = models.ForeignKey(Goods,on_delete=models.CASCADE, verbose_name='商品编号',null=True)
    itme_id = models.ForeignKey(Order, on_delete=models.CASCADE, verbose_name='订单编号', null=True)

    # itme_id = models.IntegerField('hehe', null=True)   #更改外键约束后才能清空所约束的表
    # def __str__(self):
    #     return self.name


django/shopping_mall/shopping/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.core import validators
from .models import User


class RegisterForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = UserCreationForm.Meta.fields

    email = forms.EmailField()

django/shopping_mall/shopping/views.py
from django.shortcuts import render,redirect
from django.core.exceptions import ObjectDoesNotExist,MultipleObjectsReturned
from django.http import HttpResponse,JsonResponse
from django.contrib.auth.forms import AuthenticationForm
from .forms import RegisterForm
from django.contrib.auth import login as auth_login,logout as auth_logout
#导入auth中的login(登录)和logout(退出)并取别名
from .models import Goods_type,Goods,Addr,User,Banner,Shop_cart,Pay_type,Order,Order_goods
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
import json,time,pymysql,os
from whoosh.filedb.filestore import FileStorage
from whoosh.fields import *
from jieba.analyse import ChineseAnalyzer
from whoosh.qparser import QueryParser

def create_index(request):
    analyzer = ChineseAnalyzer()
    schema = Schema(
        ids = TEXT(stored=True,analyzer=analyzer),
        name = TEXT(stored=True,analyzer=analyzer)
    )
    file_storage = FileStorage('D:/Chihuo/shopping_mall/index')
    if not os.path.exists('D:/Chihuo/shopping_mall/index'):
        os.mkdir('D:/Chihuo/shopping_mall/index')
        ix = file_storage.create_index(schema)
    else:
        ix = file_storage.open_index()
    writer = ix.writer()
    for goods in Goods.objects.all():
        writer.add_document(ids=str(goods.id),name=goods.name)
        print(goods.name)
    writer.commit()
    return HttpResponse('创建完成')

 #搜索查询
def search(request):
    keywords = request.GET.get('p')
    file_storage = FileStorage('D:/Chihuo/shopping_mall/index')
    ix = file_storage.open_index()
    with ix.searcher() as searcher:
        query = QueryParser('name',ix.schema).parse(keywords)
        results = searcher.search(query,limit=None)
        lis=[]
        for res in results:
            # print(res)
            lis.append(int(res.get('ids')))
    if request.user.is_authenticated:
        user1 = User.objects.get(username=request.user)
        num = Shop_cart.objects.filter(user_id=user1.id).count()
    else:
        num = 0
    tj = Goods.objects.filter(tj = 1).all()
    page1=Goods.objects.filter(id__in=lis)
    if page1:
        page=page1
    else:
        page = Goods.objects.filter(name__contains=keywords)
        #print(page)
    context={
        'page':page,
        'tj':tj,
        'num':num
    }
    return render(request,'list1.html',context)


#登录
def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request=request,data=request.POST)
        if form.is_valid():
            user = form.get_user() # 获取当前登录的用户对象
            auth_login(request,user=user)
            return redirect(request.POST.get('next','homepage'))
    else:
        form = AuthenticationForm()
    context = {
        'form':form,
        'next':request.GET.get('next','homepage')
    }
    return render(request, 'login.html', context)

#首页
def homepage(request):
    if request.user.is_authenticated:
        user = request.user
        user1 = User.objects.get(username=user)
        num = Shop_cart.objects.filter(user_id=user1.id).count()
    else:
        num = 0
    # request.session['num'] = num
    banner = Banner.objects.filter(title=1,status=1).all()
    jingtai = Banner.objects.filter(title=0,status=1).all()
    fenlei = Goods_type.objects.all()
    goods = Goods.objects.filter(zyxs=1).all()
    context = {
        'banner':banner,
        'jingtai':jingtai,
        'fenlei':fenlei,
        'num':num,
        'goods':goods
    }
    return render(request,'homepage.html',context)

#退出
def logout(request):
    auth_logout(request)
    return redirect('homepage')

#注册
def register(request):
    if request.method == 'POST':
        form = RegisterForm(data=request.POST)
        email = request.POST.get('email')
        if form.is_valid():
            a=form.save()
            b=User.objects.filter(username=a).update(email=email)
            return redirect('login')
    else:
        form = RegisterForm()
    # print(form.errors)
    context = {
        'form':form
    }
    return render(request, 'register.html', context)

#用户信息
@login_required
def user_center_info(request):
    user = request.user
    user1 = User.objects.get(username=user)
    return render(request,'user_center_info.html',{'user1':user1})

#购物车
@login_required
def cart(request):#gwc:购物车
    user_id = User.objects.get(username=request.user).id #获取当前登录用户的id
    gwc = Shop_cart.objects.filter(user_id=user_id).all() #获取当前用户的购物车
    if request.user.is_authenticated:
        user = request.user
        user1 = User.objects.get(username=user)
        num = Shop_cart.objects.filter(user_id=user1.id).count()
    else:
        num = 0
    context = {
        'gwc':gwc,
        'num':num
    }
    return render(request,'cart.html',context)

#商品详情
def detail(request,a):
    if request.user.is_authenticated:
        user = request.user
        user1 = User.objects.get(username=user)
        num = Shop_cart.objects.filter(user_id=user1.id).count()
    else:
        num = 0
    tj = Goods.objects.filter(tj = 1).all() #tj:推荐商品
    xq = Goods.objects.get(id=a) #xq:详情
    fl = Goods_type.objects.get(id=xq.goods_id)#fl:分类
    context = {
        'xq': xq,
        'tj': tj,
        'fl':fl,
        'num':num
    }
    return render(request,'detail.html',context)

#商品分类
def list(request,a,b=1):
    if request.user.is_authenticated:
        user1 = User.objects.get(username=request.user)
        num = Shop_cart.objects.filter(user_id=user1.id).count()
    else:
        num = 0
    # num = request.session.get('num')
    tj = Goods.objects.filter(tj = 1).all() #tj:推荐商品
    quanbu = Goods.objects.filter(goods_id=a).all()
    fl = Goods_type.objects.get(id=a) #fl:分类
    paginator = Paginator(quanbu,4)
    page = paginator.get_page(b)
    b=b
    context = {
        'tj': tj,
        'fl':fl,
        'page':page,
        'num':num,'b':b
    }
    return render(request,'list.html',context)

#添加地址
def user_center_site(request):
    name = request.user
    user = User.objects.get(username=name)
    if request.method == 'POST':
        name = request.POST.get('name')
        site = request.POST.get('site')
        zip_code = request.POST.get('Zip_Code')
        tel = request.POST.get('tel')
        if name and site and zip_code and tel:
            goods = Addr.objects.create(name=name, site=site, Zip_Code=zip_code, tel=tel,user_id=user.id)
            if goods:
                res = {"aaa":"添加成功"}
            else:
                res = {"aaa":"添加失败"}
            return JsonResponse(res)
        else:
            res = {"aaa":"数据不能为空！"}
            return JsonResponse(res)

    else:
        addr = Addr.objects.filter(user_id=user.id).all()
        context = {
            'addr': addr
        }
        return render(request,'user_center_site.html',context)

#购物车添加数据
@login_required
def shop(request):
    user_id = User.objects.get(username=request.user).id
    id1 = request.GET.get('id1')
    num1 = request.GET.get('num')
    cart1 = Shop_cart.objects.filter(goods1_id=id1,user_id=user_id).all()
    if cart1:
        num3 = Shop_cart.objects.get(goods1_id=id1,user_id=user_id).count  #获取物品已有数量
        num2 = num3 + int(num1)
        shop_gx = Shop_cart.objects.filter(user_id=user_id,goods1_id=id1).update(count=num2)
    else:
        shop = Shop_cart.objects.create(goods1_id=id1,user_id=user_id,count=num1)
    res = {'b':'成功'}
    return JsonResponse(res)

#立即购买
@login_required
def goumai(request):
    user_id = User.objects.get(username=request.user).id
    id1 = request.GET.get('ids')
    id1 = json.loads(id1)
    num1 = request.GET.get('num')           #ljgm:立即购买
    num1 = json.loads(num1)
    user_id = User.objects.get(username=request.user).id  # 获取当前登录用户的id
    itme_id = str(int(time.time() * 100)) + str(int(time.clock() * 100))
    order = Order.objects.create(user_id=user_id, itmes=itme_id, order_status=0, status=0)
    itme = Order.objects.get(itmes=itme_id)
    price = Goods.objects.get(id=id1[0]).price
    order_goods = Order_goods.objects.create(itme_id_id=itme.id, goods_id=id1[0], num1=num1[0])
    addr = Addr.objects.filter(user_id=user_id).all()
    pay = Pay_type.objects.filter(status=1).all()
    wdd = Order_goods.objects.filter(itme_id_id=itme.id).all()
    context = {
        'addr':addr,
        'pay':pay,
        'wdd':wdd
    }
    return render(request, 'place_order.html', context)
    # if shop:
    #     return render(request,'place_order.html',context)
    # else:
    #     res = {'b':'连接失败'}
    #     return JsonResponse(res)

#增减购物车商品数量
def gai(request):
    goodsid = request.GET.get('goodsid')
    count = request.GET.get('count')
    user_id = User.objects.get(username=request.user).id
    gai = Shop_cart.objects.filter(user_id=user_id,goods1_id=goodsid).update(count=count)
    if gai:
        res = {'a':'成功'}
    else:
        res = {'a':'修改失败'}
    return JsonResponse(res)

#删除购物车的商品
def dell(request,q):
    shop_id = Shop_cart.objects.get(id=q).delete()
    return redirect('cart')

#购物车  wdd:未付款订单
def place_order(request):
    id=request.GET.get('id')
    id1= json.loads(id)
    user_id = User.objects.get(username=request.user).id  # 获取当前登录用户的id
    itme_id = str(int(time.time() * 100)) + str(int(time.clock() * 100))
    order = Order.objects.create(user_id=user_id, itmes=itme_id,order_status=0,status=0)
    itme = Order.objects.get(itmes=itme_id)
    for i in id1:
        num = Shop_cart.objects.get(user_id=user_id, goods1_id=i).count
        price = Goods.objects.get(id=i).price
        order_goods = Order_goods.objects.create(itme_id_id=itme.id, goods_id=i, num1=num)
        if order and order_goods:
            shop_gx = Shop_cart.objects.filter(goods1_id=i).delete()

django/shopping_mall/shopping/templates/detail.html
{% extends "homepage.html" %}
{% load static category %}
{% block main %}
	<div class="search_bar clearfix">
		<a href="{% url 'homepage' %}" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="search_con fl">
            <form action="{% url 'search' %}">
			<input type="text" class="input_text fl" name="p" placeholder="搜索商品">
			<input type="submit" class="input_btn fr" name="" value="搜索">
            </form>
		</div>
		<div class="guest_cart fr">
			<a href="{% url 'cart' %}" class="cart_name fl">我的购物车</a>

            <div class="goods_count fl" id="show_count">{{ num }}</div>
		</div>
	</div>
	<div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>	
				<span></span>			
				<ul class="subnav">
                    {% get_categories as categories %}
                    {% for category in categories %}
					    <li><a href="{% url 'list' category.id %}" class="{{ category.icon }}">{{ category.name }}</a></li>
					{% endfor %}
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="{% url 'homepage' %}">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="breadcrumb">
		<a href="#">全部分类</a>
		<span>></span>
		<a href="">{{ fl.name }}</a>
		<span>></span>
		<a href="#">商品详情</a>
	</div>
{% block fenlei %}
	<div class="goods_detail_con clearfix">
		<div class="goods_detail_pic fl"><img src="{{ MEDIA_URL }}{{ xq.img1 }}" style="width:100%;height:100%;"></div>

		<div class="goods_detail_list fr">
			<em id="id1" style="display:none;">{{ xq.id }}</em>
			<h3>{{ xq.name }}</h3>
			<p>天天生鲜向您保证所售商品均为正品行货，天天生鲜自营商品开具机打发票或电子发票。</p>
			<div class="prize_bar">
				<span class="show_pirze">¥<em id="danjia">{{ xq.price }}</em></span>
				<span class="show_unit">单  位：500g</span>
			</div>
			<div class="goods_num clearfix">
				<div class="num_name fl">数 量：</div>
				<div class="num_add fl">
					<input type="text" class="num_show fl" value="1" id="shuliang">
					<a href="javascript:;" class="add fr" id="jiahao">+</a>
					<a href="javascript:;" class="minus fr" id="jianhao">-</a>
				</div> 
			</div>
			<div class="total">总价：<em id="zongjia">{{ xq.price }}</em>元</div>
			<div class="operate_btn">
				<a href="javascript:;" class="buy_btn" id="buy_btn">立即购买</a>
				{% if user.is_authenticated %}
					<a href="javascript:;" class="add_cart" id="add_cart">加入购物车</a>
				{% else %}
					<a href="{% url 'shop' %}" class="add_cart">加入购物车</a>
				{% endif %}
			</div>
		</div>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
					{% for t in tj %}
					<li>
						<a href="{% url 'detail' t.id %}"><img src="{{ MEDIA_URL }}{{ t.img1 }}"></a>
						<h4><a href="{% url 'detail' t.id %}">{{ t.name }}</a></h4>
						<div class="prize">￥{{ t.price }}</div>
					</li>
					{% endfor %}
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<ul class="detail_tab clearfix">
				<li class="active">商品介绍</li>
				<li>评论</li>
			</ul>

			<div class="tab_content">
				<dl>
					<dt>商品详情：</dt>
					<dd>{{ xq.goods_info }}</dd>
				</dl>
			</div>

		</div>
	</div>

	<div class="add_jump"></div>

	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/jquery.cookie.js' %}"></script>
	<script type="text/javascript">

		$('#add_cart').click(function(){
			var a=$('#shuliang').val();
			var b=$('#id1').text();
			console.log(a,b);
			$.ajax({
				url:'http://127.0.0.1:8000/shop/',
				type:'get',
				data:{
					'num':a,
					'id1':b
				},
				dataType:'json',
				success:function (res) {
					$(alert(res.b),$(window.location.reload()))}
			})
			return false
		});

		$('#jiahao').mousedown(function () {
            var num = $('#shuliang').val();
            if($('#shuliang').val() < 910)
            {
              	$('#shuliang').val(function () {
                return num * 1 + 1;
            	});
			}
			var num1 = parseInt($('#shuliang').val());
		    var num2 = parseFloat($('#danjia').html());
			$('#zongjia').html(function () {
			    return ((num1*100)*(num2*100)/10000).toFixed(2);
			});
        });

		$('#jianhao').mousedown(function () {
            var num = $('#shuliang').val();
            if($('#shuliang').val() > 1)
            {
              	$('#shuliang').val(function () {
                return num * 1 - 1;
            	});
			}
			var num1 = parseInt($('#shuliang').val());
		    var num2 = parseFloat($('#danjia').html());
			$('#zongjia').html(function () {
			    return ((num1*100)*(num2*100)/10000).toFixed(2);
			});
        });

		$('#shuliang').change(function(){
		    $('#shuliang').val(function () {
				return parseInt($('#shuliang').val());
            });
		    jieguo();
		    if($('#shuliang').val()<1){
			    $('#shuliang').val(1);
				jieguo();
			}
			else if($('#shuliang').val() > 910){
			    $('#shuliang').val(910);
			    jieguo();
			}
		});

		function jieguo() {
		    var num1 = parseInt($('#shuliang').val());
		    var num2 = parseFloat($('#danjia').html());
			$('#zongjia').html(function () {
			    return ((num1*100)*(num2*100)/10000).toFixed(2);
			});
        };

		// $('#add_cart').mousedown(function () {
		//
		// 	location.href = "/cart/updatecart/add/0/45/"+$('#shuliang').val();
		//
        // });
		//
		$("#buy_btn").click(function(){
			var a= [$('#shuliang').val()];
			var b= [$('#id1').text()];
			console.log(a,b);
			$(this).attr('href','/goumai/?num=' + JSON.stringify(a) + '&ids=' + JSON.stringify(b));
		});
	</script>
{% endblock %}
{% endblock %}

django/shopping_mall/shopping/templates/user_center_order.html
{% extends "cart.html" %}
{% load static %}
{% block qian %}
	<div class="search_bar clearfix">
		<a href="{% url 'homepage' %}" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
    {% endblock %}
    {% block hou %}
	</div>

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'user_center_info' %}">· 个人信息</a></li>
				<li><a href="{% url 'user_center_order' %}" class="active">· 全部订单</a></li>
				<li><a href="{% url 'user_center_site' %}">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">全部订单</h3>
            {% if dd %}
                {% for i in dd %}
				<ul class="order_list_th w978 clearfix">
					<li class="col01">{{ i.ctime }}</li>
					<li class="col02">订单号:<em>{{ i.itmes }}</em></li>
{#                    <input type="text" style="display: none" class="dd" data-id="{{ i.id }}">#}
					<li class="col02 stress">{{ i.get_order_status_display }}</li>
				</ul>

				<table class="order_list_table w980">
					<tbody>
						<tr>
							<td width="55%" class="hh hi">
                                {% for j in i.order_goods_set.all %}
                                    <ul class="order_goods_list clearfix">
                                        <li class="col01"><img src="{{ MEDIA_URL }}{{ j.goods.img1 }}"></li>
                                        <li class="col02">{{ j.goods.name }}<em class="price">{{ j.goods.price }}</em>元/{{ i.goods.unit }}</li>
                                        <li class="col03">{{ j.num1 }}</li>
                                        <li class="col04"></li>
                                    </ul>
                                {% endfor %}
							</td>
							<td width="15%" class="zongjia"></td>
							<td width="15%">{{ i.get_order_status_display }}</td>
							<td width="15%"><a href="#" class="oper_btn">{{ i.get_status_display }}</a>
                            <input style="display: none" type="text" id="dd" value="{{ i.id }}">
                            </td>
						</tr>
					</tbody>
				</table>
                {% endfor %}
				<div class="pagenation">
					<a href="#"><上一页</a>
					<a href="#" class="active">1</a>
					<a href="#">2</a>
					<a href="#">3</a>
					<a href="#">4</a>
					<a href="#">5</a>
					<a href="#">下一页></a>
				</div>
            {% else %}
                <h1 style="text-align:center;font-size: 16px;color: #c6c6c5">您的还没有购买过商品！</h1>
            {% endif %}
		</div>
	</div>

    <script>
        $('.oper_btn').click(function () {
        var data=[];
        var a=parseInt($(this).next('#dd').val());
        data.push(a);
			console.log(a); //在控制台Console查看数据
        $(this).attr('href', '/qfk/?id=' + JSON.stringify(data));
        });

        //计算小计
        xiaoji();
        function xiaoji(){
            $('.hi').change(function(){
                var xiaoji=0;
                $(this).find('.order_goods_list').find('.price').each(function () {
                    var num1 = parseFloat($(this).text());
                    var num2 = parseInt($(this).parent().next('.col03').text());
                    console.log(num1,num2);
                    xiaoji = ((num1*100)*(num2*100)/10000).toFixed(2)+'元';
                    console.log(xiaoji);
                    $(this).parent().next().next('.col04').text(xiaoji);
                });
            })
         }

        $('.col01').ready(function () {
            $('.hi').change()
         });

        //总金额
        zongji();
        function zongji(){
            $('.hh').change(function () {
                var zongjia=0;
                $(this).find('.order_goods_list').find('.col04').each(function () {
                    zongjia += parseFloat($(this).text());
                });
                $(this).next('.zongjia').text((zongjia).toFixed(2) + '元');
                console.log(zongjia);
            });
         }

        $('.ul').ready(function () {
            $('.hh').change()
         })



    </script>

{% endblock %}